base:
  samples: ["AN"]  # AN currently
  input:
    AN: "data/base/pgcAN2.2019-07.vcf.tsv"
  output:
    AN: "results/AN/base/QC/AN_GSR_BASE.QC.gz"

target:
  genotype:
    bed: "data/target/genotype/ukb_imp_allchr_v3_40k_fmri.bed"
    bim: "data/target/genotype/ukb_imp_allchr_v3_40k_fmri.bim"
    fam: "data/target/genotype/ukb_imp_allchr_v3_40k_fmri.fam"
    prefix: "data/target/genotype/ukb_imp_allchr_v3_40k_fmri"
  phenotype: "data/target/phenotype/phenotype.txt"
  
results:
  AN:
    qc_prefix_prefix: "results/AN/target/QC"
    final_target_prefix: "results/AN/target/final"

prs:
  AN:
    output_prefix: "results/AN/prs"


mapping:
  AN: 
    CHROM: CHR
    ID: SNP
    POS: BP
    REF: A1
    ALT: A2
    IMPINFO: INFO
    PVAL: P
    BETA: BETA
    OR: "NA"
    
